services:
  customer-service:
    build: ./customer-service
    ports:
      - "8001:8000"
    volumes:
      - ./customer-service:/customer-app

  product-service:
    build: ./product-service
    ports:
      - "8002:8000"
    volumes: 
    - ./product-service:/product-app

