apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: customer-db
spec:
  serviceName: customer-db
  replicas: 1
  selector:
    matchLabels:
      app: customer-db
  template:
    metadata:
      labels:
        app: customer-db
    spec:
      containers:
      - name: customer-db
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
          - name: DB_HOST
            value: "customer-db"
          - name: DB_USER
            valueFrom:
              secretKeyRef:   
                name: customer-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:        
              secretKeyRef:
                name: customer-secret
                key: DB_PASSWORD
          - name: DB_NAME
            value: "customerdb"
  volumeClaimTemplates:
  - metadata:
      name: customer-db-storage
    spec:
      storageClassName: hostpath
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: customer-db
spec:
  selector:
    app: customer-db
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None   
