apiVersion: v1
kind: PersistentVolume
metadata:
  name: customer-db-pv-volume
  labels:
    type: customer-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customerdb-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi


---

apiVersion: v1
kind: Service
metadata:
  name: customer-db
spec:
  ports:
  - port: 3306
  selector:
    app: customerdb
  clusterIP: None


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerdb-deployment
spec:
  selector:
    matchLabels:
      app: customerdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: customerdb
    spec:
      containers:
      - image: mysql:latest
        name: customerdb-deployment
        env: #Define variables / where to find them.

          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: customer-secret
                key: ROOT_PASSWORD


          - name: MYSQL_DATABASE
            value: "customerdb"


          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: customer-secret
                key: DB_USER


          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: customer-secret
                key: DB_PASSWORD

        ports:
        - containerPort: 3306
          name: customer-db

        volumeMounts:
        - name: customerdb-persistent-storage
          mountPath: /var/lib/mysql
          
      volumes:
      - name: customerdb-persistent-storage
        persistentVolumeClaim:
          claimName: customerdb-pv-claim