apiVersion: v1
kind: PersistentVolume
metadata:
  name: product-db-pv-volume
  labels:
    type: product-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/product-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: productdb-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi


---

apiVersion: v1
kind: Service
metadata:
  name: product-db
spec:
  ports:
  - port: 3306
  selector:
    app: productdb
  clusterIP: None


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productdb-deployment
spec:
  selector:
    matchLabels:
      app: productdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: productdb
    spec:
      containers:
      - image: mysql:latest
        name: productdb-deployment
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: product-secret
                key: ROOT_PASSWORD
          - name: MYSQL_DATABASE
            value: "productdb"
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: product-secret
                key: DB_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: product-secret
                key: DB_PASSWORD
        ports:
        - containerPort: 3306
          name: product-db
        volumeMounts:
        - name: productdb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: productdb-persistent-storage
        persistentVolumeClaim:
          claimName: productdb-pv-claim