#File contains deployment and service for the microservices: Product-service, customer-service
#Deployment and service for databases and adminer are separate file.
#Secret defined in additional yaml-file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment 
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 1 #Starting with only one replica. Could be scaled via "kubectl"
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-container
        image: markusceder/product-service:v25

        env: #Grabbing "sensitive" information about the database. Used for the backend to be able to communicate with the db.
          - name: DB_HOST
            value: "product-db"
          - name: DB_USER
            valueFrom:
              secretKeyRef:   
                name: product-secret
                key: DB_USER

          - name: DB_PASSWORD
            valueFrom:        
              secretKeyRef:
                name: product-secret
                key: DB_PASSWORD

          - name: DB_NAME
            value: "productdb"

---

apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP #using kluser IP when services should not be used from the outside



---





apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  selector:
    matchLabels:
      app: customer-service
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: markusceder/customer-service:v27
        env:
          - name: DB_HOST
            value: "customer-db"
          - name: DB_USER
            valueFrom:
              secretKeyRef:   
                name: customer-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:        
              secretKeyRef:
                name: customer-secret
                key: DB_PASSWORD
          - name: DB_NAME
            value: "customerdb"

---

apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1 
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: markusceder/frontend:v25
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: frontend